### ISSUE TITLE
Please change output for listing date

### ISSUE THREAD

**Issue by jc4balos** [Elleined/marketplace-api#3]
![image](https://github.com/Elleined/marketplace-api/assets/66464582/3c634935-c372-46e7-8926-545cdbb2753a)

**Comment by jc4balos** [comment]
@Elleined

**Comment by Elleined** [comment]
product or orderItem?

**Comment by Elleined** [comment]
![image](https://github.com/Elleined/marketplace-api/assets/111877930/7b39a0b2-4a50-4308-ab2f-e58a9f3e357c)

**Comment by Elleined** [comment]
Goods na
